### ISSUE TITLE
Can't change mini atom-text-editor height in my package (and any other package)

### ISSUE THREAD

**Issue by KSXGitHub** [heisian/hacking-the-kernel-ui#1]
I have set stylesheet property `height` of `atom-text-editor` to `100%` but it still keep the old size, which don't fit its container, what's wrong with this?

What's `atom-text-editor` element looks like in my package:

![image](https://cloud.githubusercontent.com/assets/11488886/11843688/7dbaeeba-a43d-11e5-9184-8e866da5b68b.png)

Inspect by Dev Tool (`element.style` refers to style of `atom-text-editor` element)

![image](https://cloud.githubusercontent.com/assets/11488886/11843713/a25c8166-a43d-11e5-888a-1313eab6390b.png)

![image](https://cloud.githubusercontent.com/assets/11488886/11843759/ddacd950-a43d-11e5-8a40-afb9a20d4638.png)

**Comment by heisian** [comment]
Could you post a fullscreen shot of the editor?  I'm not sure in what context you're seeing this element.

**Comment by KSXGitHub** [comment]
This is screenshot of my package, `atom-text-editor.mini` in this context just has the same size (same height) with any other mini text editor (in any other package):

Displaying in your ui:
![image](https://cloud.githubusercontent.com/assets/11488886/11861187/450a1776-a4b0-11e5-8e0e-ef44f9f069fa.png)

Displaying in another ui - one-dark-ui:
![image](https://cloud.githubusercontent.com/assets/11488886/11861209/7a4c7fbe-a4b0-11e5-8ff2-49deee8e230c.png)

My package has not been completed yet, so, it isn't available for apm, but I may publish if you want to take a look.

Also, I ask you two things:
1. If you know how to fix this, please tell me which commit, (I have forked your repo yesterday).
2. If you know which less variable defines this stylesheet property, please tell me (I may change some styles in my package).

(I don't want to close this issue, I just accidently click close button)

**Comment by KSXGitHub** [comment]
Also, I think I somehow figured it out:

What's this property? Is that located in your `ui-variables.less`?

![image](https://cloud.githubusercontent.com/assets/11488886/11861347/d8b1d814-a4b1-11e5-89c8-e86fe38583ac.png)

**Comment by heisian** [comment]
That property is not in my variables.. so you are making a console command package and would like the area where you enter commands to be full height of the editor?

It looks like you'd need to adjust the height of the parent `<atom-pane-container class="panes">`

BTW.. this seems like a really useful package.  running terminal from atom would be great!

**Comment by KSXGitHub** [comment]
Thank for your compliment,

Back to the problem, I checked that again, by changing `atom-text-editor` height to a greater value and change ui to `one-dark-ui`, `atom-text-editor` doesn't change its height. Therefore, this is not an issue of your package, this issue is closed.

Also, do you know that variable (which determine height of that `atom-text-editor`)? I can make the editor has the same height with the button (`Enter`), but I think it would be better if I make the button has a height equal to that variable.
